spring.application.name=government-grant-disbursement-system

# Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/government_subsidy_db
spring.datasource.username=root
spring.datasource.password=Mysql123

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# MySQL Dialect
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect